// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ptIXnRhtcTpiSM1uFKGX6B4hAXMzVVs',
    appId: '1:401642995837:web:3cabe3449e430484e83114',
    messagingSenderId: '401642995837',
    projectId: 'flut-tube-3da78',
    authDomain: 'flut-tube-3da78.firebaseapp.com',
    storageBucket: 'flut-tube-3da78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD86eKVQQGpdd1PzaZQeWP8yuf3FKLpkxo',
    appId: '1:401642995837:android:59ca58eeadcfa41ee83114',
    messagingSenderId: '401642995837',
    projectId: 'flut-tube-3da78',
    storageBucket: 'flut-tube-3da78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJX0sfNQ798lj55akKRLkPq94TvemLvg8',
    appId: '1:401642995837:ios:4618638c21cfb394e83114',
    messagingSenderId: '401642995837',
    projectId: 'flut-tube-3da78',
    storageBucket: 'flut-tube-3da78.appspot.com',
    iosBundleId: 'com.example.flutTube',
  );
}
